// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/lynn9388/blockchain-sharding/p2p/network.proto

package p2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common "github.com/lynn9388/blockchain-sharding/common"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingPong_Message int32

const (
	PingPong_PING PingPong_Message = 0
	PingPong_PONG PingPong_Message = 1
)

var PingPong_Message_name = map[int32]string{
	0: "PING",
	1: "PONG",
}
var PingPong_Message_value = map[string]int32{
	"PING": 0,
	"PONG": 1,
}

func (x PingPong_Message) String() string {
	return proto.EnumName(PingPong_Message_name, int32(x))
}
func (PingPong_Message) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_network_60857c5a8f5052de, []int{0, 0}
}

type PingPong struct {
	Message              PingPong_Message `protobuf:"varint,1,opt,name=message,proto3,enum=p2p.PingPong_Message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PingPong) Reset()         { *m = PingPong{} }
func (m *PingPong) String() string { return proto.CompactTextString(m) }
func (*PingPong) ProtoMessage()    {}
func (*PingPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_network_60857c5a8f5052de, []int{0}
}
func (m *PingPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingPong.Unmarshal(m, b)
}
func (m *PingPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingPong.Marshal(b, m, deterministic)
}
func (dst *PingPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingPong.Merge(dst, src)
}
func (m *PingPong) XXX_Size() int {
	return xxx_messageInfo_PingPong.Size(m)
}
func (m *PingPong) XXX_DiscardUnknown() {
	xxx_messageInfo_PingPong.DiscardUnknown(m)
}

var xxx_messageInfo_PingPong proto.InternalMessageInfo

func (m *PingPong) GetMessage() PingPong_Message {
	if m != nil {
		return m.Message
	}
	return PingPong_PING
}

func init() {
	proto.RegisterType((*PingPong)(nil), "p2p.PingPong")
	proto.RegisterEnum("p2p.PingPong_Message", PingPong_Message_name, PingPong_Message_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiscoverNodeClient is the client API for DiscoverNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscoverNodeClient interface {
	Ping(ctx context.Context, in *PingPong, opts ...grpc.CallOption) (*PingPong, error)
	GeiNeighborNodes(ctx context.Context, in *common.Node, opts ...grpc.CallOption) (DiscoverNode_GeiNeighborNodesClient, error)
}

type discoverNodeClient struct {
	cc *grpc.ClientConn
}

func NewDiscoverNodeClient(cc *grpc.ClientConn) DiscoverNodeClient {
	return &discoverNodeClient{cc}
}

func (c *discoverNodeClient) Ping(ctx context.Context, in *PingPong, opts ...grpc.CallOption) (*PingPong, error) {
	out := new(PingPong)
	err := c.cc.Invoke(ctx, "/p2p.DiscoverNode/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoverNodeClient) GeiNeighborNodes(ctx context.Context, in *common.Node, opts ...grpc.CallOption) (DiscoverNode_GeiNeighborNodesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DiscoverNode_serviceDesc.Streams[0], "/p2p.DiscoverNode/GeiNeighborNodes", opts...)
	if err != nil {
		return nil, err
	}
	x := &discoverNodeGeiNeighborNodesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DiscoverNode_GeiNeighborNodesClient interface {
	Recv() (*common.Node, error)
	grpc.ClientStream
}

type discoverNodeGeiNeighborNodesClient struct {
	grpc.ClientStream
}

func (x *discoverNodeGeiNeighborNodesClient) Recv() (*common.Node, error) {
	m := new(common.Node)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DiscoverNodeServer is the server API for DiscoverNode service.
type DiscoverNodeServer interface {
	Ping(context.Context, *PingPong) (*PingPong, error)
	GeiNeighborNodes(*common.Node, DiscoverNode_GeiNeighborNodesServer) error
}

func RegisterDiscoverNodeServer(s *grpc.Server, srv DiscoverNodeServer) {
	s.RegisterService(&_DiscoverNode_serviceDesc, srv)
}

func _DiscoverNode_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingPong)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoverNodeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p.DiscoverNode/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoverNodeServer).Ping(ctx, req.(*PingPong))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoverNode_GeiNeighborNodes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(common.Node)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiscoverNodeServer).GeiNeighborNodes(m, &discoverNodeGeiNeighborNodesServer{stream})
}

type DiscoverNode_GeiNeighborNodesServer interface {
	Send(*common.Node) error
	grpc.ServerStream
}

type discoverNodeGeiNeighborNodesServer struct {
	grpc.ServerStream
}

func (x *discoverNodeGeiNeighborNodesServer) Send(m *common.Node) error {
	return x.ServerStream.SendMsg(m)
}

var _DiscoverNode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "p2p.DiscoverNode",
	HandlerType: (*DiscoverNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DiscoverNode_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GeiNeighborNodes",
			Handler:       _DiscoverNode_GeiNeighborNodes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/lynn9388/blockchain-sharding/p2p/network.proto",
}

func init() {
	proto.RegisterFile("github.com/lynn9388/blockchain-sharding/p2p/network.proto", fileDescriptor_network_60857c5a8f5052de)
}

var fileDescriptor_network_60857c5a8f5052de = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8f, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x13, 0x2c, 0xb6, 0x0c, 0x55, 0xc2, 0x82, 0x20, 0x01, 0x41, 0x72, 0x10, 0x2f, 0xee,
	0xca, 0xf6, 0xd2, 0xde, 0x85, 0xe0, 0xc1, 0x18, 0x3c, 0x7a, 0x4b, 0x36, 0xc3, 0x66, 0x6d, 0x33,
	0xb3, 0x64, 0xa3, 0xe2, 0xbf, 0x97, 0x26, 0xf6, 0x90, 0x9b, 0xb7, 0xfd, 0xf6, 0xcd, 0xf7, 0x98,
	0x81, 0x9d, 0x75, 0x43, 0xfb, 0x59, 0x4b, 0xc3, 0x9d, 0x3a, 0xfc, 0x10, 0xed, 0x36, 0xdb, 0xad,
	0xaa, 0x0f, 0x6c, 0xf6, 0xa6, 0xad, 0x1c, 0x3d, 0x84, 0xb6, 0xea, 0x1b, 0x47, 0x56, 0x79, 0xed,
	0x15, 0xe1, 0xf0, 0xcd, 0xfd, 0x5e, 0xfa, 0x9e, 0x07, 0x16, 0x67, 0x5e, 0xfb, 0xf4, 0xdf, 0xbe,
	0xe1, 0xae, 0x63, 0x52, 0xc4, 0x0d, 0x4e, 0x7e, 0xf6, 0x0e, 0xab, 0xd2, 0x91, 0x2d, 0x99, 0xac,
	0x50, 0xb0, 0xec, 0x30, 0x84, 0xca, 0xe2, 0x75, 0x7c, 0x1b, 0xdf, 0x5f, 0xea, 0x2b, 0xe9, 0xb5,
	0x97, 0xa7, 0x5c, 0xbe, 0x4c, 0xe1, 0xdb, 0x69, 0x2a, 0xbb, 0x81, 0xe5, 0xdf, 0x9f, 0x58, 0xc1,
	0xa2, 0x7c, 0x2e, 0xf2, 0x24, 0x1a, 0x5f, 0xaf, 0x45, 0x9e, 0xc4, 0xfa, 0x03, 0xd6, 0x4f, 0x2e,
	0x18, 0xfe, 0xc2, 0xbe, 0xe0, 0x06, 0xc5, 0x1d, 0x2c, 0x8e, 0x5d, 0xe2, 0x62, 0x56, 0x9b, 0xce,
	0x31, 0x8b, 0x84, 0x86, 0x24, 0x47, 0x57, 0xa0, 0xb3, 0x6d, 0xcd, 0xa3, 0x1a, 0xc4, 0x5a, 0x4e,
	0xbb, 0xcb, 0x23, 0xa6, 0x33, 0xca, 0xa2, 0xc7, 0xb8, 0x3e, 0x1f, 0xcf, 0xd9, 0xfc, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x5c, 0xab, 0x00, 0xd1, 0x4b, 0x01, 0x00, 0x00,
}
